# @package _global_

cartpole:
  # State constraint
  safety_set:
    x: [-0.9, 0.9]
    x_dot: [-15, 15]
    theta: [-0.8, 0.8]
    theta_dot: [-15, 15]

  # Action constraint
  force_bound: [-30, 30]

  # Cart-pole (Physical model parameters)
  mass_cart: 0.94
  mass_pole: 0.23
  length_pole: 0.64
  friction_cart: 18
  friction_pole: 0.0031
  gravity: 9.8    # gravitational acceleration
  frequency: 30   # Runtime frequency
  with_friction: true
  kinematics_integrator: "euler"
  terminate_on_failure: true

  # Cart-pole (Control settings)
  initial_condition: [
    0.41401618443072785,
    -0.8718992596679117,
    -0.5441679004386896,
    3.9533094574574275,
    false
  ]
  set_point: [
    0.0,
    0.0,
    0.0,
    0.0
  ]
  random_reset:
    seed: 0   # Random seed
    train: true
    eval: true

  # Add random noise to actuator/friction
  random_noise:
    seed: 0   # Random seed

    # Actuator noise
    actuator:
      apply: false
      type: "gaussian"
      mean: 0
      stddev: 2

    # Friction noise
    friction:
      # cart friction
      cart:
        apply: false
        type: "gaussian"
        mean: 0
        stddev: 2

      # pole friction
      pole:
        apply: false
        type: "gaussian"
        mean: 0
        stddev: 2

  # RL Reward from Envs
  reward:
    action_penalty: 0.0
    crash_penalty: 0.0
    high_performance_reward_factor: 0
    lyapunov_form: 'Phy-DRL'      # Lyapunov Reward Form of Phy-DRL or UCB
    lyapunov_reward_factor: 1


